root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server/main.go"
  bin = "tmp/server"
  full_bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  stop_on_error = true

[log]
  time = true
